language: node_js
node_js: stable

install: 
  - npm install


script: 
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "shsgear"
  - git config user.email "shsgear@qq.com"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${githubBlog}@${GH_REF}" master:master


branches:
  only:
    - blog-src


env:
 global:
   - GH_REF: github.com/Shsgear/Shsgear.github.io.git